const usernames = [
    'ACGOG',
    'theCreedo',
    'DillonA',
    'Soso',
    'BiggerFish',
    'BruteLee',
    'Bread1999',
    'Creuss',
    'Damios',
    'Drasu5',
    'Frostymate',
    'Grendel',
    'gategeek',
    'Happybandito',
    'HeavyRainism',
    'Klondlike',
    'McRamsey',
    'Not_Quite_Right',
    'PressingPickle',
    'princebolverk',
    'RainierKoala',
    'REAPER OF SOULS',
    'Rob Croy',
    'samuraih69',
    'thesandwichgrinch',
    'SapphireKirbo',
    'theDeltaNiner',
    'TacoDefender',
    'thesirthejames',
    'Trio_GG',
    'Xann101',
    'Lord Balliel',
    'Jules.McCools',
    'Wurlitzer',
    'MalZenith',
    'Wumpafruit',
    'Markacia',
    'Copium Ascension',
    'MomoChi',
    'Bon Bon',
    'Aryenna',
    'AppleJacks',
    'Azyril',
    'Actual_Pokemon_Master',
    'looseleaftea'
];

const emails = [
    'john.doe@fakemail.com',
    'jane.doe@placeholdermail.net',
    'alex.smith@dummydomain.org',
    'emily.johnson@sampledomain.com',
    'michael.brown@testmail.net',
    'linda.white@fictitiousemail.com',
    'david.martinez@mockmail.org',
    'sarah.miller@simulatedmail.com',
    'brian.lee@fakeinbox.net',
    'lisa.perez@tempmail.org',
    'robert.jones@imaginarymail.com',
    'maria.garcia@virtualmail.net',
    'charles.williams@simulatemail.org',
    'betty.davis@fauxinbox.com',
    'peter.martinez@phantomemail.net',
    'laura.taylor@constructmail.com',
    'kevin.lopez@fabricatedmail.org',
    'rebecca.lewis@illusorymail.com',
    'samuel.wilson@makebelieve.net',
    'olivia.moore@createdmail.org',
    'andrew.thompson@mythicalmail.com',
    'sophia.clark@fictivemail.net',
    'daniel.hernandez@inventmail.org',
    'nancy.lee@fabricateinbox.com',
    'joshua.hall@testdomain.net',
    'katherine.allen@simulatemail.com',
    'christopher.young@virtualpost.org',
    'patricia.king@dreammail.com',
    'matthew.wright@illusionmail.net',
    'ashley.lopez@fakemailbox.org',
    'jacob.hill@mockinbox.com',
    'angela.scott@mythpost.net',
    'ryan.green@fantasymail.org',
    'megan.adams@constructedmail.com',
    'ethan.baker@pretendpost.net',
    'rachel.nelson@imitationmail.org',
    'kimberly.carter@fablemail.com',
    'gregory.mitchell@storymail.net',
    'susan.perez@legendmail.org',
    'brandon.roberts@makeupmail.com',
    'laura.phillips@inventpost.net',
    'bradley.turner@mythinbox.org',
    'amanda.campbell@fictiveemail.com',
    'steven.parker@synthmail.net',
    'melissa.evans@mockpost.org'
]

const thoughts = [
    'Why is “abbreviation” such a long word?',
    'I’m on a seafood diet. I see food and I eat it.',
    'Is it just me or does coffee taste better on Fridays?',
    'I wish my wallet came with free refills.',
    'Why is Monday so far from Friday, but Friday so close to Monday?',
    'Life is short. Smile while you still have teeth.',
    'I’m not arguing, I’m just explaining why I’m right.',
    'My bed is a magical place where I suddenly remember everything I forgot to do.',
    'If we aren’t supposed to have midnight snacks, why is there a light in the fridge?',
    'I need a six-month holiday, twice a year.',
    'Sunglasses allow you to stare at people without getting caught. It’s like Facebook in real life.',
    'Why do they call it beauty sleep when you wake up looking like a troll?',
    'I’m on that new diet where you eat everything and hope for a miracle.',
    'I’m not lazy, I’m on energy-saving mode.',
    'Do I run? Yes, out of time, patience, and money.',
    'There’s no “we” in fries.',
    'Chocolate is the answer. Who cares what the question is?',
    'I followed my heart and it led me to the fridge.',
    'Be strong, I whispered to my WiFi signal.',
    'A balanced diet means a cupcake in each hand.',
    'Why does cooking take like 5 hours and eating like 3 seconds?',
    'I’m just a girl, standing in front of a salad, asking it to be a donut.',
    'Exercise? I thought you said extra fries!',
    'I’m not late. I’m just early for tomorrow.',
    'My favorite exercise is a cross between a lunge and a crunch. I call it lunch.',
    'Just once, I want my life to be like an 80’s movie, preferably with a really awesome musical number for no apparent reason.',
    'I walk around like everything is fine, but deep down, inside my shoe, my sock is sliding off.',
    'I’m not saying I’m a wizard, I’m just saying no one has ever seen me and a wizard in the same room together.',
    'Trying to be a functioning adult is like trying to bake a cake without a recipe. You know you need flour, but that’s about it.',
    'I hate it when I go to hug someone really sexy and my face smashes right into the mirror.',
    '“Adulting” is just whispering “why is this happening to me” every time something goes wrong.',
    'My daily routine: Wake up, be awesome, go back to sleep.',
    'I’m not weird, I’m limited edition.',
    'The road to success is dotted with many tempting parking spaces.',
    'I put the “pro” in procrastinate.',
    'Life update: currently holding it all together with one bobby pin.',
    'I’m not arguing, I’m simply explaining why I’m right and you’re wrong.',
    'My bed is a magical place where I can remember all the things I was supposed to do.',
    'If you see me talking to myself, I’m having a staff meeting.',
    'I don’t need a hair stylist, my pillow gives me a new hairstyle every morning.',
    'I’m not clumsy. It’s just the floor hates me, the tables and chairs are bullies, and the walls get in my way.',
    'Why be moody when you can shake yo booty?',
    'I’m not lazy, I’m in energy-saving mode.',
    'Remember, if the world didn’t suck, we’d all fall off.',
    'I’m not weird. I’m a limited edition.',
    'I’m not arguing. I’m simply explaining why I’m correct.',
    'I’m not late. I’m just early for tomorrow.',
    'Being an adult is like folding a fitted sheet. No one really knows how.',
    'Why do they call it rush hour when nothing moves?',
    'Sometimes I talk to myself because I need expert advice.'
]

const reactions = [
    'I Agree',
    'Excuse me, what?',
    'I see what you mean',
    'Speechless',
    'I vibe with this',
    'Magical!',
    'Big Sigh',
    'Goosebumps',
    'Wholesome',
    'Absolutely Amazing!'
]

module.exports = {
    usernames,
    emails,
    thoughts,
    reactions
}